String test = "This\tstring\thas\ttabs\nand\nnewlines";
String test1 = "this\0string\0has\0null\characters";
String escape_test = "this \
has an escaped newline.";

String escape_test_2 = "this string has an \" escaped quote!";


String empty = ""


"This string
is not escaped"

String escaped_a = "\a should be a"

String too_long = "hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello"

String too_long_new_line = "hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello\
hellohellohellohellohellohellohellohellohellohellohellohello

"This string is incomplete